language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
os: linux
dist: trusty
addons:
    apt:
        packages:
        - libopenblas-dev
        - liblapack-dev
        - liblapacke-dev
install:
    - pip install coveralls
    - python setup.py install
script:
    - nosetests --with-coverage --cover-package=prox_tv
    - mkdir -p build && cd build
    - cmake -DENABLE_TESTING:BOOL=ON ../
    - cmake --build .
    - ctest -VV
after_success:
    - coveralls
